Imports System.Xml.Linq

Public Class NameGenerator
    ' List of 1000 unique first names (500 real-world + 500 sci-fi)
    Private Shared ReadOnly FirstNames As New List(Of String) From {
        "James", "Mary", "John", "Patricia", "Robert", "Jennifer", "Michael", "Linda", "William", "Elizabeth",
        "David", "Barbara", "Richard", "Susan", "Joseph", "Jessica", "Thomas", "Sarah", "Charles", "Karen",
        "Christopher", "Nancy", "Daniel", "Lisa", "Matthew", "Betty", "Andrew", "Margaret", "Mark", "Ashley",
        "Steven", "Donna", "Paul", "Michelle", "George", "Emily", "Kenneth", "Dorothy", "Edward", "Amy",
        "Brian", "Helen", "Ronald", "Deborah", "Anthony", "Laura", "Jason", "Carol", "Jeffrey", "Melissa",
        "Timothy", "Kimberly", "Kevin", "Rebecca", "Eric", "Sharon", "Donald", "Cynthia", "Gary", "Angela",
        "Stephen", "Brenda", "Larry", "Pamela", "Scott", "Nicole", "Frank", "Katherine", "Raymond", "Samantha",
        "Gregory", "Debra", "Joshua", "Rachel", "Jerry", "Catherine", "Dennis", "Carolyn", "Walter", "Janet",
        "Patrick", "Christine", "Peter", "Maria", "Harold", "Heather", "Douglas", "Diane", "Henry", "Julie",
        "Carl", "Joyce", "Arthur", "Victoria", "Ryan", "Kelly", "Roger", "Christina", "Joe", "Lauren",
        "Albert", "Joan", "Philip", "Evelyn", "Jonathan", "Ruth", "Jack", "Judith", "Adam", "Frances",
        "Benjamin", "Gloria", "Samuel", "Ann", "Nicholas", "Jean", "Bruce", "Alice", "Harry", "Teresa",
        "Alan", "Mildred", "Louis", "Stephanie", "Jeremy", "Jane", "Randy", "Lillian", "Howard", "Cheryl",
        "Eugene", "Wanda", "Craig", "Beverly", "Aaron", "Denise", "Terry", "Marilyn", "Fred", "Kathleen",
        "Russell", "Virginia", "Phillip", "Irene", "Alexander", "Bonnie", "Martin", "Tina", "Jesse", "Robin",
        "Wayne", "Doris", "Ralph", "Shirley", "Billy", "Diana", "Steve", "Anna", "Roy", "Amanda",
        "Todd", "Lori", "Bobby", "Theresa", "Willie", "Jacqueline", "Allen", "Paula", "Johnny", "Marie",
        "Jimmy", "Kathy", "Lawrence", "Rose", "Stanley", "Sandra", "Gerald", "Connie", "Keith", "Tracy",
        "Ernest", "Lois", "Vincent", "Judy", "Glenn", "Sylvia", "Jeffery", "Lynn", "Norman", "Rita",
        "Dale", "Dawn", "Barry", "Peggy", "Glen", "Holly", "Victor", "Joanne", "Leon", "Sheila",
        "Marvin", "Wendy", "Bernard", "Ellen", "Clifford", "Beth", "Tom", "Emma", "Darrell", "Tammy",
        "Herbert", "Renee", "Franklin", "Stacy", "Melvin", "Carrie", "Jerome", "Vicki", "Randall", "Kristin",
        "Duane", "Anita", "Ross", "Jill", "Max", "Valerie", "Clinton", "Gina", "Eddie", "Sherry",
        "Wesley", "Marjorie", "Nathan", "Sally", "Brad", "Danielle", "Dean", "Monica", "Lee", "Kristen",
        "Tony", "Hazel", "Chris", "June", "Edwin", "Ruby", "Jay", "Edna", "Neil", "Lydia",
        "Jacob", "Clara", "Joel", "Florence", "Ben", "Louise", "Ted", "Arlene", "Darryl", "Naomi",
        "Calvin", "Gladys", "Jon", "Eleanor", "Kurt", "Maureen", "Kent", "Colleen", "Ricky", "Joanna",
        "Ivan", "Faye", "Lloyd", "Nora", "Earl", "Grace", "Milton", "Amber", "Rodney", "Bethany",
        "Dwayne", "Priscilla", "Roland", "Lena", "Clayton", "Kristina", "Clyde", "Melanie", "Leo", "Heidi",
        "Ron", "Michele", "Herman", "Vanessa", "Troy", "Natasha", "Rick", "Rhonda", "Andre", "Kayla",
        "Brett", "Tara", "Byron", "Erica", "Curtis", "Brooke", "Alvin", "Jenna", "Allan", "Leslie",
        "Lonnie", "Alicia", "Don", "Felicia", "Ray", "Nina", "Colin", "Candace", "Tim", "Brandy",
        "Nate", "Tamara", "Jared", "Audrey", "Evan", "Kara", "Preston", "Leah", "Alex", "Suzanne",
        "Simon", "Casey", "Zachary", "Erin", "Gabriel", "Kerry", "Isaac", "Laurie", "Shaun", "Christy",
        "Cory", "Shelly", "Lance", "Megan", "Seth", "Tiffany", "Elliot", "April", "Miles", "Jenny",
        "Luke", "Cassandra", "Owen", "Kelsey", "Dylan", "Bridget", "Gavin", "Molly", "Blake", "Rachael",
        "Caleb", "Sonia", "Trevor", "Marissa", "Ethan", "Hannah", "Micah", "Sabrina", "Elijah", "Lindsay",
        "Noah", "Abigail", "Wyatt", "Bianca", "Levi", "Chloe", "Sam", "Zoe", "Eli", "Claire",
        "Finn", "Lydia", "Grayson", "Faith", "Jasper", "Hope", "Silas", "Ivy", "Ezra", "Willow",
        "Oliver", "Sophia", "Liam", "Ava", "Mason", "Isabella", "Logan", "Mia", "Lucas", "Charlotte",
        "Henry", "Amelia", "Jack", "Harper", "Owen", "Evelyn", "Aiden", "Ella", "Jackson", "Scarlett",
        "Carter", "Grace", "Luke", "Lily", "Jayden", "Natalie", "Dylan", "Layla", "Gabriel", "Riley",
        "Isaac", "Zoey", "Evan", "Nora", "Caleb", "Hazel", "Wyatt", "Addison", "Levi", "Aubrey",
        "Eli", "Brooklyn", "Nathan", "Savannah", "Ryan", "Audrey", "Max", "Claire", "Eli", "Skylar",
        "Julian", "Peyton", "Connor", "Madeline", "Landon", "Julia", "Hunter", "Aria", "Gavin", "Sadie",
        "Isaiah", "Mackenzie", "Colin", "Kaylee", "Elliot", "Morgan", "Miles", "Kylie", "Blake", "Hailey",
        "Micah", "Jocelyn", "Elijah", "Brianna", "Noah", "Camila", "Silas", "Lillian", "Ezra", "Alexa",
        "Finn", "Delilah", "Grayson", "Emery", "Jasper", "Aurora", "Seth", "Eliza", "Trevor", "Giselle",
        "Ethan", "Penelope", "Micah", "Esme", "Elijah", "Opal", "Noah", "Freya", "Wyatt", "Luna",
        "Levi", "Nova", "Sam", "Stella", "Eli", "Cora", "Finn", "Lyric", "Grayson", "Selene",
        "Zorak", "Luna", "Kael", "Vera", "Talon", "Nyx", "Ryn", "Saria", "Draven", "Elara",
        "Xan", "Zyla", "Korr", "Astra", "Vex", "Lyra", "Zane", "Thalia", "Jett", "Nova",
        "Cade", "Selene", "Bryn", "Kara", "Dax", "Mira", "Syl", "Rhea", "Torin", "Vega",
        "Kaelan", "Zara", "Rynne", "Lira", "Zev", "Aeryn", "Taz", "Cora", "Jaxon", "Nia",
        "Vorn", "Tessa", "Kyr", "Sana", "Dren", "Luna", "Xar", "Mila", "Zolt", "Eris",
        "Thane", "Zoe", "Rax", "Tara", "Vyn", "Kael", "Soren", "Nyssa", "Jyn", "Vara",
        "Kade", "Lira", "Zan", "Mira", "Tyn", "Sera", "Vax", "Nara", "Drake", "Zyla",
        "Cyrus", "Astra", "Ryn", "Lyra", "Zor", "Thalia", "Jett", "Nova", "Cade", "Selene",
        "Bryn", "Kara", "Dax", "Mira", "Syl", "Rhea", "Torin", "Vega", "Kaelan", "Zara",
        "Rynne", "Lira", "Zev", "Aeryn", "Taz", "Cora", "Jaxon", "Nia", "Vorn", "Tessa",
        "Kyr", "Sana", "Dren", "Luna", "Xar", "Mila", "Zolt", "Eris", "Thane", "Zoe",
        "Rax", "Tara", "Vyn", "Kael", "Soren", "Nyssa", "Jyn", "Vara", "Kade", "Lira",
        "Zan", "Mira", "Tyn", "Sera", "Vax", "Nara", "Drake", "Zyla", "Cyrus", "Astra",
        "Ryn", "Lyra", "Zor", "Thalia", "Jett", "Nova", "Cade", "Selene", "Bryn", "Kara",
        "Dax", "Mira", "Syl", "Rhea", "Torin", "Vega", "Kaelan", "Zara", "Rynne", "Lira",
        "Zev", "Aeryn", "Taz", "Cora", "Jaxon", "Nia", "Vorn", "Tessa", "Kyr", "Sana",
        "Dren", "Luna", "Xar", "Mila", "Zolt", "Eris", "Thane", "Zoe", "Rax", "Tara",
        "Vyn", "Kael", "Soren", "Nyssa", "Jyn", "Vara", "Kade", "Lira", "Zan", "Mira",
        "Tyn", "Sera", "Vax", "Nara", "Drake", "Zyla", "Cyrus", "Astra", "Ryn", "Lyra",
        "Zor", "Thalia", "Jett", "Nova", "Cade", "Selene", "Bryn", "Kara", "Dax", "Mira",
        "Syl", "Rhea", "Torin", "Vega", "Kaelan", "Zara", "Rynne", "Lira", "Zev", "Aeryn",
        "Taz", "Cora", "Jaxon", "Nia", "Vorn", "Tessa", "Kyr", "Sana", "Dren", "Luna",
        "Xar", "Mila", "Zolt", "Eris", "Thane", "Zoe", "Rax", "Tara", "Vyn", "Kael",
        "Soren", "Nyssa", "Jyn", "Vara", "Kade", "Lira", "Zan", "Mira", "Tyn", "Sera",
        "Vax", "Nara", "Drake", "Zyla", "Cyrus", "Astra", "Ryn", "Lyra", "Zor", "Thalia",
        "Jett", "Nova", "Cade", "Selene", "Bryn", "Kara", "Dax", "Mira", "Syl", "Rhea",
        "Torin", "Vega", "Kaelan", "Zara", "Rynne", "Lira", "Zev", "Aeryn", "Taz", "Cora",
        "Jaxon", "Nia", "Vorn", "Tessa", "Kyr", "Sana", "Dren", "Luna", "Xar", "Mila",
        "Zolt", "Eris", "Thane", "Zoe", "Rax", "Tara", "Vyn", "Kael", "Soren", "Nyssa",
        "Jyn", "Vara", "Kade", "Lira", "Zan", "Mira", "Tyn", "Sera", "Vax", "Nara",
        "Drake", "Zyla", "Cyrus", "Astra", "Ryn", "Lyra", "Zor", "Thalia", "Jett", "Nova",
        "Cade", "Selene", "Bryn", "Kara", "Dax", "Mira", "Syl", "Rhea", "Torin", "Vega",
        "Kaelan", "Zara", "Rynne", "Lira", "Zev", "Aeryn", "Taz", "Cora", "Jaxon", "Nia",
        "Vorn", "Tessa", "Kyr", "Sana", "Dren", "Luna", "Xar", "Mila", "Zolt", "Eris",
        "Thane", "Zoe", "Rax", "Tara", "Vyn", "Kael", "Soren", "Nyssa", "Jyn", "Vara",
        "Kade", "Lira", "Zan", "Mira", "Tyn", "Sera", "Vax", "Nara", "Drake", "Zyla",
        "Cyrus", "Astra", "Ryn", "Lyra", "Zor", "Thalia", "Jett", "Nova", "Cade", "Selene",
        "Bryn", "Kara", "Dax", "Mira", "Syl", "Rhea", "Torin", "Vega", "Kaelan", "Zara",
        "Rynne", "Lira", "Zev", "Aeryn", "Taz", "Cora", "Jaxon", "Nia", "Vorn", "Tessa",
        "Kyr", "Sana", "Dren", "Luna", "Xar", "Mila", "Zolt", "Eris", "Thane", "Zoe",
        "Rax", "Tara", "Vyn", "Kael", "Soren", "Nyssa", "Jyn", "Vara", "Kade", "Lira",
        "Zan", "Mira", "Tyn", "Sera", "Vax", "Nara", "Drake", "Zyla", "Cyrus", "Astra"
    }

    ' Shared Random instance to avoid reseeding issues
    Private Shared Rng As New Random()

    Public Shared Function GetRandomFirstName() As String
        If FirstNames Is Nothing OrElse FirstNames.Count = 0 Then Return "Jane" ' Fallback name
        Return FirstNames(Rng.Next(FirstNames.Count))
    End Function
End Class